routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Models\Customer;
use App\Models\InvoicePayment;
use App\Models\Offer;

Route::get('/', function () {
    $hotels = Offer::where('type', '=', 'hotel')->take(4)->get();
    $restaurants = Offer::where('type', '=', 'restaurant')->take(4)->get();


    $excursion = Offer::where('type', '=', 'excursion')->take(4)->get();
    return view('front.index', compact('hotels', 'restaurants','excursion'));
    });

Route::get('firebase_otp_verification', [HomeController::class, 'otpVerification']);

// Route::view("/", "front.index")->name('front.end.home');
// Route::get("/", "HomeController@index")->name('front.index');

Route::get('test', function(){
    return view('test');
});

// Make order ready
Route::get('/order-make-ready/{id}', 'OrderController@makeOrderReady')->name('order-make-ready');
Route::get('/order-make-ready-for-delivery/{id}', 'OrderController@makeOrderReadyForDelivery')->name('order-make-ready-for-delivery');
Route::get('/order-make-ready-for-cancelled/{id}', 'OrderController@makeOrderReadyCancelled')->name('order-make-ready-for-cancelled');
Route::get('/invoicepdf/{id}', 'OrderController@invoicePDF')->name('invoicepdf');

// Route excursion and excursionBooking
Route::get("/excursion", "ExcursionActivityController@indexFront")->name('excursion');
Route::get("/excursion-detail/{id}", "ExcursionActivityController@showFront")->name('excursion-detail');
Route::get("/formulaire-de-Reservation/{id}", "ExcursionActivityController@requestFormex")->name('request-formulaire')->middleware('customer.auth');



Route::get('checkIfUserExist','CustomerController@checkIfUserExist')->name('checkIfUserExist');
Route::get('loginUsingId','CustomerController@logUser')->name('loginUsingId');

//Customer
Route::get('/customerProfil/{id}', 'CustomerController@profil')->name('customerProfile');
Route::get('/editProfil/{id}', 'CustomerController@editProfil')->name('editProfil');
Route::put('/updateProfile/{id}', 'CustomerController@updateProfile')->name('updateProfile');

Route::get('/customerRequest/{id}', 'CustomerController@allCustomerOrders')->name('customerRequest');

// Route musee
Route::get("/musees", "MuseeController@index")->name('musee');
Route::get("/musee-detail/{id}", "MuseeController@show")->name('musee-detail');

// Route restaurant
Route::get("/restaurant-detail/{id}", "RestaurantController@show")->name('restaurant-detail');
Route::get("/view/restaurants", "RestaurantController@index");
Route::get("/view/Allrestaurants", "RestaurantController@indexAll")->name('All-restaurant');

// Route hotel, residence, HotelBooking and ResidenceBooking
Route::get("/view/hotels", "HotelController@index");
Route::get("/hotel-detail/{id}", "HotelController@show")->name('hotel-detail');
Route::get("/residence-detail/{id}", "HotelController@showes")->name('residence-detail');
// Route::get("/formulaire_Reservation/{id}", "HotelController@requestFormulaire")->name('request_formular')->middleware('customer.auth');


Route::get("/view/Allhotel", "HotelController@indexAll")->name('All-Hotel');
Route::get("/view/AllResidences", "HotelController@indexAlls")->name('All-Residences');

// Route location and locationBooking
Route::get("/location", "LocationController@index");
Route::get("/location-detail/{id}", "LocationController@show")->name('location-detail');
// Route::get("/formulaire_de_Reservation/{id}", "LocationController@requestForm")->name('request_form');
Route::get("/formulaire_de_Reservation/{id}", "LocationController@requestForm")->name('request_form')->middleware('customer.auth');

// Bedroom
Route::get("/bedroom-detail/{id}", "HotelController@ShowBedroom")->name('bedroom-detail');

// Request Formulaire
Route::get("/formulaireReservation/{id}", "HotelController@requestFormulaireBedroom")->name('request_formulaires')->middleware('customer.auth');

Route::get("/formulaireReservationResidence/{id}", "HotelController@requestFormulaireBedroom")->name('request_formular')->middleware('customer.auth');
// ->middleware('customer.auth');

Route::get('/storeAdjeminPay', "AdjeminPayController@storeAdjeminPay")->name('storeAdjeminPay');


// Route::view("/hotel-detail", "front.hotel_detail");
// Route::view("/restaurant-detail", "front.restaurant_detail");
// Route::view("/view/restaurants", "front.restaurants");
// Route::view("/view/hotels", "front.hotels");
// Route::view("/location", "front.location");

Route::view("/_", "_");    // Test view

Auth::routes(['verify' => true]);

Auth::routes(['register' => false]);

Route::get('/home', 'HomeController@index')->middleware('verified');
//
Route::resource('hotels', 'HotelController');
Route::resource('locations', 'LocationController');
Route::resource('restaurants', 'RestaurantController');

Route::name ('offer.')->middleware ('ajax')->group (function () {
    Route::prefix('offer')->group(function () {
    });
    Route::name ('rating')->put ('rating/{offer}', 'OfferController@rate');
});


Route::get('/restaurant_by_specification/{speciality}', 'RestaurantController@restaurantBySpecification');

Route::get('/excursion_by_specification/{speciality}', 'ExcursionActivityController@excursionBySpecification');


Route::resource('customers', 'CustomerController');

Route::resource('invoices', 'InvoiceController');

Route::resource('invoicePayments', 'InvoicePaymentController');

Route::resource('metaDataServices', 'MetaDataServiceController');

Route::resource('offers', 'OfferController');

Route::resource('orderItems', 'OrderItemController');

Route::resource('ownerSources', 'OwnerSourceController');

Route::resource('receipts', 'ReceiptController');

Route::resource('users', 'UserController');

Route::resource('orders', 'OrderController');

Route::resource('customerSessions', 'CustomerSessionController');

Route::resource('favoris', 'FavoriController');

Route::resource('foodSpeialties', 'FoodSpeialtiesController');

Route::resource('excursionActivities', 'ExcursionActivityController');

// Customer Routes
Route::post('/orders/storeAjax','OrderController@insertOrderData');

Route::resource('customerDevices', 'CustomerDeviceController');
Route::resource('hotelSpecifications', 'HotelSpecificationController');

Route::resource('otps', 'OtpController');


// Route::post('/orders/storeAjax', "OrderController@storeAjax")->name('orders.storeAjax');
Route::post('/orders/storeAjax', "OrderController@storeAjax")->name('orders.storeAjax');

Route::get('adjeminPay/{id}', function($id){
    // dump($id);
    $transaction = InvoicePayment::find($id);
    $payment_method = $transaction->payment_method;
    $transactionId = $transaction->payment_reference;
    $transaction_designation = $transaction->payment_gateway_designation;
    $amount = $transaction->amount;
    $status = $transaction->status;
    $customer = $transaction->creator_name;
    $customer_id = $transaction->creator_id;
    $notification = $transaction->invoice_id;
    $currency = $transaction->currency_code;
    // dd($transaction);

    if($transaction !== null){
        // return 'ok';
        return view('adjeminpay.index', compact('payment_method', 'transactionId', 'transaction_designation', 'amount','currency', 'status', 'customer', 'notification','customer_id', 'transaction'));
        // return view("cinetpay.index");
    }

});

Route::get('notify/{id}', 'AdjeminPayController@changeStatus');


// Route::get('cinetPay/{id}', function($id){
//     dd($id);

//     $transaction = InvoicePayment::find($id);
//     $payment_method = $transaction->payment_method;
//     $transactionId = $transaction->payment_reference;
//     $transaction_designation = $transaction->payment_gateway_designation;
//     $amount = $transaction->amount;
//     $status = $transaction->status;
//     $customer = $transaction->creator_name;
//     $customer_id = $transaction->creator_id;
//     $notification = $transaction->invoice_id;

//     if($transaction !== null){
//         // return 'ok';
//         // return view("cinetpay.index");
//         return view('cinetpay.index', compact('payment_method', 'transactionId', 'transaction_designation', 'amount', 'status', 'customer', 'notification','customer_id'));
//     }
// });


Route::resource('transcations', 'TranscationController');

app/MetaDataService.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * @SWG\Definition(
 *      definition="MetaDataService",
 *      required={""},
 *      @SWG\Property(
 *          property="id",
 *          description="id",
 *          type="integer",
 *          format="int32"
 *      ),
 *      @SWG\Property(
 *          property="created_at",
 *          description="created_at",
 *          type="string",
 *          format="date-time"
 *      ),
 *      @SWG\Property(
 *          property="updated_at",
 *          description="updated_at",
 *          type="string",
 *          format="date-time"
 *      )
 * )
 */
class MetaDataService extends Model
{
    use SoftDeletes;

    public $table = 'meta_data_service';
    
    const CREATED_AT = 'created_at';
    const UPDATED_AT = 'updated_at';


    protected $dates = ['deleted_at'];



    public $fillable = [
        
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        
    ];

    
}

app/Models/MetaDataService.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * @SWG\Definition(
 *      definition="MetaDataService",
 *      required={""},
 *      @SWG\Property(
 *          property="id",
 *          description="id",
 *          type="integer",
 *          format="int32"
 *      ),
 *      @SWG\Property(
 *          property="created_at",
 *          description="created_at",
 *          type="string",
 *          format="date-time"
 *      ),
 *      @SWG\Property(
 *          property="updated_at",
 *          description="updated_at",
 *          type="string",
 *          format="date-time"
 *      )
 * )
 */
class MetaDataService extends Model
{
    use SoftDeletes;

    public $table = 'meta_data_service';
    
    const CREATED_AT = 'created_at';
    const UPDATED_AT = 'updated_at';


    protected $dates = ['deleted_at'];



    public $fillable = [
        
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        
    ];

    
}

app/Models/__/MetaDataService.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * @SWG\Definition(
 *      definition="MetaDataService",
 *      required={""},
 *      @SWG\Property(
 *          property="id",
 *          description="id",
 *          type="integer",
 *          format="int32"
 *      ),
 *      @SWG\Property(
 *          property="created_at",
 *          description="created_at",
 *          type="string",
 *          format="date-time"
 *      ),
 *      @SWG\Property(
 *          property="updated_at",
 *          description="updated_at",
 *          type="string",
 *          format="date-time"
 *      )
 * )
 */
class MetaDataService extends Model
{
    use SoftDeletes;

    public $table = 'meta_data_service';
    
    const CREATED_AT = 'created_at';
    const UPDATED_AT = 'updated_at';


    protected $dates = ['deleted_at'];



    public $fillable = [
        
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        
    ];

    
}

app/Http/Controllers/MetaDataServiceController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateMetaDataServiceRequest;
use App\Http\Requests\UpdateMetaDataServiceRequest;
use App\Repositories\MetaDataServiceRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;
use Response;

class MetaDataServiceController extends AppBaseController
{
    /** @var  MetaDataServiceRepository */
    private $metaDataServiceRepository;

    public function __construct(MetaDataServiceRepository $metaDataServiceRepo)
    {
        $this->metaDataServiceRepository = $metaDataServiceRepo;
    }

    /**
     * Display a listing of the MetaDataService.
     *
     * @param Request $request
     *
     * @return Response
     */
    public function index(Request $request)
    {
        $metaDataServices = $this->metaDataServiceRepository->all();

        return view('meta_data_services.index')
            ->with('metaDataServices', $metaDataServices);
    }

    /**
     * Show the form for creating a new MetaDataService.
     *
     * @return Response
     */
    public function create()
    {
        return view('meta_data_services.create');
    }

    /**
     * Store a newly created MetaDataService in storage.
     *
     * @param CreateMetaDataServiceRequest $request
     *
     * @return Response
     */
    public function store(CreateMetaDataServiceRequest $request)
    {
        $input = $request->all();

        $metaDataService = $this->metaDataServiceRepository->create($input);

        Flash::success('Meta Data Service saved successfully.');

        return redirect(route('metaDataServices.index'));
    }

    /**
     * Display the specified MetaDataService.
     *
     * @param int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $metaDataService = $this->metaDataServiceRepository->find($id);

        if (empty($metaDataService)) {
            Flash::error('Meta Data Service not found');

            return redirect(route('metaDataServices.index'));
        }

        return view('meta_data_services.show')->with('metaDataService', $metaDataService);
    }

    /**
     * Show the form for editing the specified MetaDataService.
     *
     * @param int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $metaDataService = $this->metaDataServiceRepository->find($id);

        if (empty($metaDataService)) {
            Flash::error('Meta Data Service not found');

            return redirect(route('metaDataServices.index'));
        }

        return view('meta_data_services.edit')->with('metaDataService', $metaDataService);
    }

    /**
     * Update the specified MetaDataService in storage.
     *
     * @param int $id
     * @param UpdateMetaDataServiceRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateMetaDataServiceRequest $request)
    {
        $metaDataService = $this->metaDataServiceRepository->find($id);

        if (empty($metaDataService)) {
            Flash::error('Meta Data Service not found');

            return redirect(route('metaDataServices.index'));
        }

        $metaDataService = $this->metaDataServiceRepository->update($request->all(), $id);

        Flash::success('Meta Data Service updated successfully.');

        return redirect(route('metaDataServices.index'));
    }

    /**
     * Remove the specified MetaDataService from storage.
     *
     * @param int $id
     *
     * @throws \Exception
     *
     * @return Response
     */
    public function destroy($id)
    {
        $metaDataService = $this->metaDataServiceRepository->find($id);

        if (empty($metaDataService)) {
            Flash::error('Meta Data Service not found');

            return redirect(route('metaDataServices.index'));
        }

        $this->metaDataServiceRepository->delete($id);

        Flash::success('Meta Data Service deleted successfully.');

        return redirect(route('metaDataServices.index'));
    }
}

resources/views/meta_data_services/create.blade.php
@extends('layouts.app')

@section('content')
    <ol class="breadcrumb">
      <li class="breadcrumb-item">
         <a href="{!! route('metaDataServices.index') !!}">Meta Data Service</a>
      </li>
      <li class="breadcrumb-item active">Créer</li>
    </ol>
     <div class="container-fluid">
          <div class="animated fadeIn">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="card">
                            <div class="card-header">
                                <i class="fa fa-plus-square-o fa-lg"></i>
                                <strong>Create Meta Data Service</strong>
                            </div>
                            <div class="card-body">
                                {!! Form::open(['route' => 'metaDataServices.store']) !!}

                                   @include('meta_data_services.fields')

                                {!! Form::close() !!}
                            </div>
                        </div>
                    </div>
                </div>
           </div>
    </div>
@endsection

resources/views/meta_data_services/edit.blade.php
@extends('layouts.app')

@section('content')
    <ol class="breadcrumb">
          <li class="breadcrumb-item">
             <a href="{!! route('metaDataServices.index') !!}">Meta Data Service</a>
          </li>
          <li class="breadcrumb-item active">Modifier</li>
        </ol>
    <div class="container-fluid">
         <div class="animated fadeIn">
             <div class="row">
                 <div class="col-lg-12">
                      <div class="card">
                          <div class="card-header">
                              <i class="fa fa-edit fa-lg"></i>
                              <strong>Modifier Meta Data Service</strong>
                          </div>
                          <div class="card-body">
                              {!! Form::model($metaDataService, ['route' => ['metaDataServices.update', $metaDataService->id], 'method' => 'patch']) !!}

                              @include('meta_data_services.fields')

                              {!! Form::close() !!}
                            </div>
                        </div>
                    </div>
                </div>
         </div>
    </div>
@endsection

resources/views/meta_data_services/fields.blade.php
<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{{ route('metaDataServices.index') }}" class="btn btn-secondary">Cancel</a>
</div>

resources/views/meta_data_services/index.blade.php
@extends('layouts.app')

@section('content')
    <ol class="breadcrumb">
        <li class="breadcrumb-item">Meta Data Services</li>
    </ol>
    <div class="container-fluid">
        <div class="animated fadeIn">
             @include('flash::message')
             <div class="row">
                 <div class="col-lg-12">
                     <div class="card">
                         <div class="card-header">
                             <i class="fa fa-align-justify"></i>
                             MetaDataServices
                             <a class="pull-right" href="{{ route('metaDataServices.create') }}"><i class="fa fa-plus-square fa-lg"></i></a>
                         </div>
                         <div class="card-body">
                             @include('meta_data_services.table')
                              <div class="pull-right mr-3">
                                     
                              </div>
                         </div>
                     </div>
                  </div>
             </div>
         </div>
    </div>
@endsection

resources/views/meta_data_services/show.blade.php
@extends('layouts.app')

@section('content')
     <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="{{ route('metaDataServices.index') }}">Meta Data Service</a>
            </li>
            <li class="breadcrumb-item active">Detail</li>
     </ol>
     <div class="container-fluid">
          <div class="animated fadeIn">
                 <div class="row">
                     <div class="col-lg-12">
                         <div class="card">
                             <div class="card-header">
                                 <strong>Details</strong>
                                  <a href="{{ route('metaDataServices.index') }}" class="btn btn-light">Back</a>
                             </div>
                             <div class="card-body">
                                 @include('meta_data_services.show_fields')
                             </div>
                         </div>
                     </div>
                 </div>
          </div>
    </div>
@endsection

resources/views/meta_data_services/table.blade.php
<div class="box">

    <!-- /.box-header -->
    <div class="box-body" style="overflow-x: scroll;">
      <table id="example" class="table table-bordered table-hover display nowrap margin-top-10 table-responsive-sm">
        <thead>
            <tr>
            <th>Action</th>
        </tr>
        </thead>
        <tbody>
        @foreach($metaDataServices as $metaDataService)
            <tr>
                
                <td>
                    {!! Form::open(['route' => ['metaDataServices.destroy', $metaDataService->id], 'method' => 'delete']) !!}
                    <div class='btn-group'>
                        <a href="{{ route('metaDataServices.show', [$metaDataService->id]) }}" class='btn btn-ghost-success'><i class="fa fa-eye"></i></a>
                        <a href="{{ route('metaDataServices.edit', [$metaDataService->id]) }}" class='btn btn-ghost-info'><i class="fa fa-edit"></i></a>
                        {!! Form::button('<i class="fa fa-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-ghost-danger', 'onclick' => "return confirm('Are you sure?')"]) !!}
                    </div>
                    {!! Form::close() !!}
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>
</div>