routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Models\Customer;
use App\Models\InvoicePayment;
use App\Models\Offer;

Route::get('/', function () {
    $hotels = Offer::where('type', '=', 'hotel')->take(4)->get();
    $restaurants = Offer::where('type', '=', 'restaurant')->take(4)->get();


    $excursion = Offer::where('type', '=', 'excursion')->take(4)->get();
    return view('front.index', compact('hotels', 'restaurants','excursion'));
    });

Route::get('firebase_otp_verification', [HomeController::class, 'otpVerification']);

// Route::view("/", "front.index")->name('front.end.home');
// Route::get("/", "HomeController@index")->name('front.index');

Route::get('test', function(){
    return view('test');
});

// Make order ready
Route::get('/order-make-ready/{id}', 'OrderController@makeOrderReady')->name('order-make-ready');
Route::get('/order-make-ready-for-delivery/{id}', 'OrderController@makeOrderReadyForDelivery')->name('order-make-ready-for-delivery');
Route::get('/order-make-ready-for-cancelled/{id}', 'OrderController@makeOrderReadyCancelled')->name('order-make-ready-for-cancelled');
Route::get('/invoicepdf/{id}', 'OrderController@invoicePDF')->name('invoicepdf');

// Route excursion and excursionBooking
Route::get("/excursion", "ExcursionActivityController@indexFront")->name('excursion');
Route::get("/excursion-detail/{id}", "ExcursionActivityController@showFront")->name('excursion-detail');
Route::get("/formulaire-de-Reservation/{id}", "ExcursionActivityController@requestFormex")->name('request-formulaire')->middleware('customer.auth');



Route::get('checkIfUserExist','CustomerController@checkIfUserExist')->name('checkIfUserExist');
Route::get('loginUsingId','CustomerController@logUser')->name('loginUsingId');

//Customer
Route::get('/customerProfil/{id}', 'CustomerController@profil')->name('customerProfile');
Route::get('/editProfil/{id}', 'CustomerController@editProfil')->name('editProfil');
Route::put('/updateProfile/{id}', 'CustomerController@updateProfile')->name('updateProfile');

Route::get('/customerRequest/{id}', 'CustomerController@allCustomerOrders')->name('customerRequest');

// Route musee
Route::get("/musees", "MuseeController@index")->name('musee');
Route::get("/musee-detail/{id}", "MuseeController@show")->name('musee-detail');

// Route restaurant
Route::get("/restaurant-detail/{id}", "RestaurantController@show")->name('restaurant-detail');
Route::get("/view/restaurants", "RestaurantController@index");
Route::get("/view/Allrestaurants", "RestaurantController@indexAll")->name('All-restaurant');

// Route hotel, residence, HotelBooking and ResidenceBooking
Route::get("/view/hotels", "HotelController@index");
Route::get("/hotel-detail/{id}", "HotelController@show")->name('hotel-detail');
Route::get("/residence-detail/{id}", "HotelController@showes")->name('residence-detail');
// Route::get("/formulaire_Reservation/{id}", "HotelController@requestFormulaire")->name('request_formular')->middleware('customer.auth');


Route::get("/view/Allhotel", "HotelController@indexAll")->name('All-Hotel');
Route::get("/view/AllResidences", "HotelController@indexAlls")->name('All-Residences');

// Route location and locationBooking
Route::get("/location", "LocationController@index");
Route::get("/location-detail/{id}", "LocationController@show")->name('location-detail');
// Route::get("/formulaire_de_Reservation/{id}", "LocationController@requestForm")->name('request_form');
Route::get("/formulaire_de_Reservation/{id}", "LocationController@requestForm")->name('request_form')->middleware('customer.auth');

// Bedroom
Route::get("/bedroom-detail/{id}", "HotelController@ShowBedroom")->name('bedroom-detail');

// Request Formulaire
Route::get("/formulaireReservation/{id}", "HotelController@requestFormulaireBedroom")->name('request_formulaires')->middleware('customer.auth');

Route::get("/formulaireReservationResidence/{id}", "HotelController@requestFormulaireBedroom")->name('request_formular')->middleware('customer.auth');
// ->middleware('customer.auth');

Route::get('/storeAdjeminPay', "AdjeminPayController@storeAdjeminPay")->name('storeAdjeminPay');


// Route::view("/hotel-detail", "front.hotel_detail");
// Route::view("/restaurant-detail", "front.restaurant_detail");
// Route::view("/view/restaurants", "front.restaurants");
// Route::view("/view/hotels", "front.hotels");
// Route::view("/location", "front.location");

Route::view("/_", "_");    // Test view

Auth::routes(['verify' => true]);

Auth::routes(['register' => false]);

Route::get('/home', 'HomeController@index')->middleware('verified');
//
Route::resource('hotels', 'HotelController');
Route::resource('locations', 'LocationController');
Route::resource('restaurants', 'RestaurantController');

Route::name ('offer.')->middleware ('ajax')->group (function () {
    Route::prefix('offer')->group(function () {
    });
    Route::name ('rating')->put ('rating/{offer}', 'OfferController@rate');
});


Route::get('/restaurant_by_specification/{speciality}', 'RestaurantController@restaurantBySpecification');

Route::get('/excursion_by_specification/{speciality}', 'ExcursionActivityController@excursionBySpecification');


Route::resource('customers', 'CustomerController');

Route::resource('invoices', 'InvoiceController');

Route::resource('invoicePayments', 'InvoicePaymentController');

Route::resource('metaDataServices', 'MetaDataServiceController');

Route::resource('offers', 'OfferController');

Route::resource('orderItems', 'OrderItemController');

Route::resource('ownerSources', 'OwnerSourceController');

Route::resource('receipts', 'ReceiptController');

Route::resource('users', 'UserController');

Route::resource('orders', 'OrderController');

Route::resource('customerSessions', 'CustomerSessionController');

Route::resource('favoris', 'FavoriController');

Route::resource('foodSpeialties', 'FoodSpeialtiesController');

Route::resource('excursionActivities', 'ExcursionActivityController');

// Customer Routes
Route::post('/orders/storeAjax','OrderController@insertOrderData');

Route::resource('customerDevices', 'CustomerDeviceController');
Route::resource('hotelSpecifications', 'HotelSpecificationController');

Route::resource('otps', 'OtpController');


// Route::post('/orders/storeAjax', "OrderController@storeAjax")->name('orders.storeAjax');
Route::post('/orders/storeAjax', "OrderController@storeAjax")->name('orders.storeAjax');

Route::get('adjeminPay/{id}', function($id){
    // dump($id);
    $transaction = InvoicePayment::find($id);
    $payment_method = $transaction->payment_method;
    $transactionId = $transaction->payment_reference;
    $transaction_designation = $transaction->payment_gateway_designation;
    $amount = $transaction->amount;
    $status = $transaction->status;
    $customer = $transaction->creator_name;
    $customer_id = $transaction->creator_id;
    $notification = $transaction->invoice_id;
    $currency = $transaction->currency_code;
    // dd($transaction);

    if($transaction !== null){
        // return 'ok';
        return view('adjeminpay.index', compact('payment_method', 'transactionId', 'transaction_designation', 'amount','currency', 'status', 'customer', 'notification','customer_id', 'transaction'));
        // return view("cinetpay.index");
    }

});

Route::get('notify/{id}', 'AdjeminPayController@changeStatus');


// Route::get('cinetPay/{id}', function($id){
//     dd($id);

//     $transaction = InvoicePayment::find($id);
//     $payment_method = $transaction->payment_method;
//     $transactionId = $transaction->payment_reference;
//     $transaction_designation = $transaction->payment_gateway_designation;
//     $amount = $transaction->amount;
//     $status = $transaction->status;
//     $customer = $transaction->creator_name;
//     $customer_id = $transaction->creator_id;
//     $notification = $transaction->invoice_id;

//     if($transaction !== null){
//         // return 'ok';
//         // return view("cinetpay.index");
//         return view('cinetpay.index', compact('payment_method', 'transactionId', 'transaction_designation', 'amount', 'status', 'customer', 'notification','customer_id'));
//     }
// });


Route::resource('transcations', 'TranscationController');

app/Models/OrderItem.php
<?php

namespace App\Models;

use Eloquent as Model;
use App\Models\Order;
use App\Models\Offer;
use App\Models\ServicePricing;
use Illuminate\Database\Eloquent\SoftDeletes;
use Symfony\Component\HttpFoundation\ParameterBag;
use Illuminate\Support\Collection;

/**
 * @SWG\Definition(
 *      definition="OrderItem",
 *      required={""},
 *      @SWG\Property(
 *          property="id",
 *          description="id",
 *          type="integer",
 *          format="int32"
 *      ),
 *      @SWG\Property(
 *          property="order_id",
 *          description="order_id",
 *          type="integer",
 *          format="int32"
 *      ),
 *      @SWG\Property(
 *          property="meta_data",
 *          description="meta_data",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="quantity",
 *          description="quantity",
 *          type="integer",
 *          format="int32"
 *      ),
 *      @SWG\Property(
 *          property="quantity_unit",
 *          description="quantity_unit",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="unit_price",
 *          description="unit_price",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="currency_code",
 *          description="currency_code",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="total_amount",
 *          description="total_amount",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="created_at",
 *          description="created_at",
 *          type="string",
 *          format="date-time"
 *      ),
 *      @SWG\Property(
 *          property="updated_at",
 *          description="updated_at",
 *          type="string",
 *          format="date-time"
 *      ),
 *      @SWG\Property(
 *          property="deleted_at",
 *          description="deleted_at",
 *          type="string",
 *          format="date-time"
 *      )
 * )
 */
class OrderItem extends Model
{
    use SoftDeletes;

    public $table = 'order_items';

    const CREATED_AT = 'created_at';
    const UPDATED_AT = 'updated_at';


    protected $dates = ['deleted_at'];



    public $fillable = [
        'order_id',
        'meta_data_id',
        'meta_data',
        'quantity',
        'quantity_unit',
        'unit_price',
        'currency_code',
        'total_amount'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'order_id' => 'integer',
        'meta_data_id'=> 'integer',
        'meta_data' => 'string',
        'quantity' => 'integer',
        'quantity_unit' => 'string',
        'unit_price' => 'string',
        'currency_code' => 'string',
        'total_amount' => 'string'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [

    ];

    public function order()
    {
        return $this->belongsTo('App\Models\Order','order_id');
    }

    public function offer()
    {
        return $this->belongsTo('App\Models\Offer','meta_data_id');
    }

    public function getOfferAttribute(){
        $order = Order::where('id',$this->order_id)->first();
        if(empty($order)){
            return null;
        }
        return $order;
    }

    public function  servicePricing(){
        $metadataObject = new ParameterBag(Collection::make(json_decode($this->meta_data))->toArray());

        return new ServicePricing($metadataObject->get("title"), $metadataObject->get("price"), $metadataObject->get("currency"));

    }


}

app/Http/Controllers/OrderItemController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateOrderItemRequest;
use App\Http\Requests\UpdateOrderItemRequest;
use App\Repositories\OrderItemRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;
use Response;

class OrderItemController extends AppBaseController
{
    /** @var  OrderItemRepository */
    private $orderItemRepository;

    public function __construct(OrderItemRepository $orderItemRepo)
    {
        $this->orderItemRepository = $orderItemRepo;
    }

    /**
     * Display a listing of the OrderItem.
     *
     * @param Request $request
     *
     * @return Response
     */
    public function index(Request $request)
    {
        if(auth()->user()){
        } else {
            return redirect(route("login"));
        }

        $orderItems = $this->orderItemRepository->all();

        return view('order_items.index')
            ->with('orderItems', $orderItems);
    }

    /**
     * Show the form for creating a new OrderItem.
     *
     * @return Response
     */
    public function create()
    {
        if(auth()->user()){
        } else {
            return redirect(route("login"));
        }

        return view('order_items.create');
    }

    /**
     * Store a newly created OrderItem in storage.
     *
     * @param CreateOrderItemRequest $request
     *
     * @return Response
     */
    public function store(CreateOrderItemRequest $request)
    {
        if(auth()->user()){
        } else {
            return redirect(route("login"));
        }

        $input = $request->all();

        $orderItem = $this->orderItemRepository->create($input);

        Flash::success('Order Item saved successfully.');

        return redirect(route('orderItems.index'));
    }

    /**
     * Display the specified OrderItem.
     *
     * @param int $id
     *
     * @return Response
     */
    public function show($id)
    {
        if(auth()->user()){
        } else {
            return redirect(route("login"));
        }

        $orderItem = $this->orderItemRepository->find($id);

        if (empty($orderItem)) {
            Flash::error('Order Item not found');

            return redirect(route('orderItems.index'));
        }

        return view('order_items.show')->with('orderItem', $orderItem);
    }

    /**
     * Show the form for editing the specified OrderItem.
     *
     * @param int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        if(auth()->user()){
        } else {
            return redirect(route("login"));
        }

        $orderItem = $this->orderItemRepository->find($id);

        if (empty($orderItem)) {
            Flash::error('Order Item not found');

            return redirect(route('orderItems.index'));
        }

        return view('order_items.edit')->with('orderItem', $orderItem);
    }

    /**
     * Update the specified OrderItem in storage.
     *
     * @param int $id
     * @param UpdateOrderItemRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateOrderItemRequest $request)
    {
        if(auth()->user()){
        } else {
            return redirect(route("login"));
        }

        $orderItem = $this->orderItemRepository->find($id);

        if (empty($orderItem)) {
            Flash::error('Order Item not found');

            return redirect(route('orderItems.index'));
        }

        $orderItem = $this->orderItemRepository->update($request->all(), $id);

        Flash::success('Order Item updated successfully.');

        return redirect(route('orderItems.index'));
    }

    /**
     * Remove the specified OrderItem from storage.
     *
     * @param int $id
     *
     * @throws \Exception
     *
     * @return Response
     */
    public function destroy($id)
    {
        if(auth()->user()){
        } else {
            return redirect(route("login"));
        }

        $orderItem = $this->orderItemRepository->find($id);

        if (empty($orderItem)) {
            Flash::error('Order Item not found');

            return redirect(route('orderItems.index'));
        }

        $this->orderItemRepository->delete($id);

        Flash::success('Order Item deleted successfully.');

        return redirect(route('orderItems.index'));
    }
}

resources/views/order_items/create.blade.php
@extends('layouts.app')

@section('content')
    <ol class="breadcrumb">
      <li class="breadcrumb-item">
         <a href="{!! route('orderItems.index') !!}">Order Item</a>
      </li>
      <li class="breadcrumb-item active">Create</li>
    </ol>
     <div class="container-fluid">
          <div class="animated fadeIn">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="card">
                            <div class="card-header">
                                <i class="fa fa-plus-square-o fa-lg"></i>
                                <strong>Create Order Item</strong>
                            </div>
                            <div class="card-body">
                                {!! Form::open(['route' => 'orderItems.store']) !!}

                                   @include('order_items.fields')

                                {!! Form::close() !!}
                            </div>
                        </div>
                    </div>
                </div>
           </div>
    </div>
@endsection

resources/views/order_items/edit.blade.php
@extends('layouts.app')

@section('content')
    <ol class="breadcrumb">
          <li class="breadcrumb-item">
             <a href="{!! route('orderItems.index') !!}">Order Item</a>
          </li>
          <li class="breadcrumb-item active">Edit</li>
        </ol>
    <div class="container-fluid">
         <div class="animated fadeIn">
             <div class="row">
                 <div class="col-lg-12">
                      <div class="card">
                          <div class="card-header">
                              <i class="fa fa-edit fa-lg"></i>
                              <strong>Edit Order Item</strong>
                          </div>
                          <div class="card-body">
                              {!! Form::model($orderItem, ['route' => ['orderItems.update', $orderItem->id], 'method' => 'patch']) !!}

                              @include('order_items.fields')

                              {!! Form::close() !!}
                            </div>
                        </div>
                    </div>
                </div>
         </div>
    </div>
@endsection

resources/views/order_items/fields.blade.php
<!-- Order Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('order_id', 'Order Id:') !!}
    {!! Form::number('order_id', null, ['class' => 'form-control']) !!}
</div>

<!-- Meta Data Field -->
<div class="form-group col-sm-12 col-lg-12">
    {!! Form::label('meta_data', 'Meta Data:') !!}
    {!! Form::textarea('meta_data', null, ['class' => 'form-control']) !!}
</div>

<!-- Quantity Field -->
<div class="form-group col-sm-6">
    {!! Form::label('quantity', 'Quantity:') !!}
    {!! Form::number('quantity', null, ['class' => 'form-control']) !!}
</div>

<!-- Quantity Unit Field -->
<div class="form-group col-sm-6">
    {!! Form::label('quantity_unit', 'Quantity Unit:') !!}
    {!! Form::text('quantity_unit', null, ['class' => 'form-control']) !!}
</div>

<!-- Unit Price Field -->
<div class="form-group col-sm-6">
    {!! Form::label('unit_price', 'Unit Price:') !!}
    {!! Form::text('unit_price', null, ['class' => 'form-control']) !!}
</div>

<!-- Currency Code Field -->
<div class="form-group col-sm-6">
    {!! Form::label('currency_code', 'Currency Code:') !!}
    {!! Form::text('currency_code', null, ['class' => 'form-control']) !!}
</div>

<!-- Total Amount Field -->
<div class="form-group col-sm-6">
    {!! Form::label('total_amount', 'Total Amount:') !!}
    {!! Form::text('total_amount', null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{{ route('orderItems.index') }}" class="btn btn-secondary">Cancel</a>
</div>

resources/views/order_items/index.blade.php
@extends('layouts.app')
@section("css")
    <link rel="stylesheet" type="text/css" href="https://coreui.io/demo/vendors/datatables.net-bs4/css/dataTables.bootstrap4.css">

@endsection

@section('content')
    <ol class="breadcrumb">
        <li class="breadcrumb-item">Offres Commandées</li>
    </ol>
    <div class="container-fluid">
        <div class="animated fadeIn">
             @include('flash::message')
             <div class="row">
                 <div class="col-lg-12">
                     <div class="card">
                         <div class="card-header">
                             <i class="fa fa-align-justify"></i>
                             Offre Commandé
                             <a class="pull-right" href="{{ route('orderItems.create') }}"><i class="fa fa-plus-square fa-lg"></i></a>
                         </div>
                         <div class="card-body">
                             @include('order_items.table')
                              <div class="pull-right mr-3">
                                     
                              </div>
                         </div>
                     </div>
                  </div>
             </div>
         </div>
    </div>
@endsection

resources/views/order_items/show.blade.php
@extends('layouts.app')

@section('content')
     <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="{{ route('orderItems.index') }}">Order Item</a>
            </li>
            <li class="breadcrumb-item active">Detail</li>
     </ol>
     <div class="container-fluid">
          <div class="animated fadeIn">
                 <div class="row">
                     <div class="col-lg-12">
                         <div class="card">
                             <div class="card-header">
                                 <strong>Details</strong>
                                  <a href="{{ route('orderItems.index') }}" class="btn btn-light">Back</a>
                             </div>
                             <div class="card-body">
                                 @include('order_items.show_fields')
                             </div>
                         </div>
                     </div>
                 </div>
          </div>
    </div>
@endsection

resources/views/order_items/show_fields.blade.php
<!-- Order Id Field -->
<div class="form-group">
    {!! Form::label('order_id', 'Order Id:') !!}
    <p>{{ $orderItem->order_id }}</p>
</div>

<!-- Meta Data Field -->
<div class="form-group">
    {!! Form::label('meta_data', 'Meta Data:') !!}
    <p>{{ $orderItem->meta_data }}</p>
</div>

<!-- Quantity Field -->
<div class="form-group">
    {!! Form::label('quantity', 'Quantity:') !!}
    <p>{{ $orderItem->quantity }}</p>
</div>

<!-- Quantity Unit Field -->
<div class="form-group">
    {!! Form::label('quantity_unit', 'Quantity Unit:') !!}
    <p>{{ $orderItem->quantity_unit }}</p>
</div>

<!-- Unit Price Field -->
<div class="form-group">
    {!! Form::label('unit_price', 'Unit Price:') !!}
    <p>{{ $orderItem->unit_price }}</p>
</div>

<!-- Currency Code Field -->
<div class="form-group">
    {!! Form::label('currency_code', 'Currency Code:') !!}
    <p>{{ $orderItem->currency_code }}</p>
</div>

<!-- Total Amount Field -->
<div class="form-group">
    {!! Form::label('total_amount', 'Total Amount:') !!}
    <p>{{ $orderItem->total_amount }}</p>
</div>

resources/views/order_items/table.blade.php
<div class="box">

    <!-- /.box-header -->
    <div class="box-body" style="overflow-x: scroll;">
      <table id="example" class="table table-bordered table-hover display nowrap margin-top-10 table-responsive-sm">
        <thead>
            <tr>
            <th>Identifiant de la commande</th>
            <th>Identifiant de l'offre</th>
            <th>Quantité</th>
            <th>Prix unitaire</th>
            <th>Code de la devise</th>
            <th>Montant total</th>
            <th>Action</th>
        </tr>
        </thead>
        <tbody>
            {{-- @dd($orderItems) --}}
            @forelse($orderItems as $orderItem)

                <tr>
                    <td>{{ $orderItem->order_id }}</td>
                    <td>{{ $orderItem->offer != null ? $orderItem->offer->title : "non renseigné"}}</td>
                    <td>{{ $orderItem->quantity }}</td>
                    <td>{{ $orderItem->unit_price }}</td>
                    <td>{{ $orderItem->currency_code }}</td>
                    <td>{{ $orderItem->total_amount }}</td>
                    <td>
                        {!! Form::open(['route' => ['orderItems.destroy', $orderItem->id], 'method' => 'delete']) !!}
                        <div class='btn-group'>
                            <a href="{{ route('orderItems.show', [$orderItem->id]) }}" class='btn btn-ghost-success'><i class="fa fa-eye"></i></a>
                            <a href="{{ route('orderItems.edit', [$orderItem->id]) }}" class='btn btn-ghost-info'><i class="fa fa-edit"></i></a>
                            {!! Form::button('<i class="fa fa-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-ghost-danger', 'onclick' => "return confirm('Are you sure?')"]) !!}
                        </div>
                        {!! Form::close() !!}
                    </td>
                </tr>
            @empty
                <div class="d-flex justify-content-center">
                    Aucune commande éffectuée.
                </div>
            @endforelse
        </tbody>
    </table>
</div>
</div>