routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Models\Customer;
use App\Models\InvoicePayment;
use App\Models\Offer;

Route::get('/', function () {
    $hotels = Offer::where('type', '=', 'hotel')->take(4)->get();
    $restaurants = Offer::where('type', '=', 'restaurant')->take(4)->get();


    $excursion = Offer::where('type', '=', 'excursion')->take(4)->get();
    return view('front.index', compact('hotels', 'restaurants','excursion'));
    });

Route::get('firebase_otp_verification', [HomeController::class, 'otpVerification']);

// Route::view("/", "front.index")->name('front.end.home');
// Route::get("/", "HomeController@index")->name('front.index');

Route::get('test', function(){
    return view('test');
});

// Make order ready
Route::get('/order-make-ready/{id}', 'OrderController@makeOrderReady')->name('order-make-ready');
Route::get('/order-make-ready-for-delivery/{id}', 'OrderController@makeOrderReadyForDelivery')->name('order-make-ready-for-delivery');
Route::get('/order-make-ready-for-cancelled/{id}', 'OrderController@makeOrderReadyCancelled')->name('order-make-ready-for-cancelled');
Route::get('/invoicepdf/{id}', 'OrderController@invoicePDF')->name('invoicepdf');

// Route excursion and excursionBooking
Route::get("/excursion", "ExcursionActivityController@indexFront")->name('excursion');
Route::get("/excursion-detail/{id}", "ExcursionActivityController@showFront")->name('excursion-detail');
Route::get("/formulaire-de-Reservation/{id}", "ExcursionActivityController@requestFormex")->name('request-formulaire')->middleware('customer.auth');



Route::get('checkIfUserExist','CustomerController@checkIfUserExist')->name('checkIfUserExist');
Route::get('loginUsingId','CustomerController@logUser')->name('loginUsingId');

//Customer
Route::get('/customerProfil/{id}', 'CustomerController@profil')->name('customerProfile');
Route::get('/editProfil/{id}', 'CustomerController@editProfil')->name('editProfil');
Route::put('/updateProfile/{id}', 'CustomerController@updateProfile')->name('updateProfile');

Route::get('/customerRequest/{id}', 'CustomerController@allCustomerOrders')->name('customerRequest');

// Route musee
Route::get("/musees", "MuseeController@index")->name('musee');
Route::get("/musee-detail/{id}", "MuseeController@show")->name('musee-detail');

// Route restaurant
Route::get("/restaurant-detail/{id}", "RestaurantController@show")->name('restaurant-detail');
Route::get("/view/restaurants", "RestaurantController@index");
Route::get("/view/Allrestaurants", "RestaurantController@indexAll")->name('All-restaurant');

// Route hotel, residence, HotelBooking and ResidenceBooking
Route::get("/view/hotels", "HotelController@index");
Route::get("/hotel-detail/{id}", "HotelController@show")->name('hotel-detail');
Route::get("/residence-detail/{id}", "HotelController@showes")->name('residence-detail');
// Route::get("/formulaire_Reservation/{id}", "HotelController@requestFormulaire")->name('request_formular')->middleware('customer.auth');


Route::get("/view/Allhotel", "HotelController@indexAll")->name('All-Hotel');
Route::get("/view/AllResidences", "HotelController@indexAlls")->name('All-Residences');

// Route location and locationBooking
Route::get("/location", "LocationController@index");
Route::get("/location-detail/{id}", "LocationController@show")->name('location-detail');
// Route::get("/formulaire_de_Reservation/{id}", "LocationController@requestForm")->name('request_form');
Route::get("/formulaire_de_Reservation/{id}", "LocationController@requestForm")->name('request_form')->middleware('customer.auth');

// Bedroom
Route::get("/bedroom-detail/{id}", "HotelController@ShowBedroom")->name('bedroom-detail');

// Request Formulaire
Route::get("/formulaireReservation/{id}", "HotelController@requestFormulaireBedroom")->name('request_formulaires')->middleware('customer.auth');

Route::get("/formulaireReservationResidence/{id}", "HotelController@requestFormulaireBedroom")->name('request_formular')->middleware('customer.auth');
// ->middleware('customer.auth');

Route::get('/storeAdjeminPay', "AdjeminPayController@storeAdjeminPay")->name('storeAdjeminPay');


// Route::view("/hotel-detail", "front.hotel_detail");
// Route::view("/restaurant-detail", "front.restaurant_detail");
// Route::view("/view/restaurants", "front.restaurants");
// Route::view("/view/hotels", "front.hotels");
// Route::view("/location", "front.location");

Route::view("/_", "_");    // Test view

Auth::routes(['verify' => true]);

Auth::routes(['register' => false]);

Route::get('/home', 'HomeController@index')->middleware('verified');
//
Route::resource('hotels', 'HotelController');
Route::resource('locations', 'LocationController');
Route::resource('restaurants', 'RestaurantController');

Route::name ('offer.')->middleware ('ajax')->group (function () {
    Route::prefix('offer')->group(function () {
    });
    Route::name ('rating')->put ('rating/{offer}', 'OfferController@rate');
});


Route::get('/restaurant_by_specification/{speciality}', 'RestaurantController@restaurantBySpecification');

Route::get('/excursion_by_specification/{speciality}', 'ExcursionActivityController@excursionBySpecification');


Route::resource('customers', 'CustomerController');

Route::resource('invoices', 'InvoiceController');

Route::resource('invoicePayments', 'InvoicePaymentController');

Route::resource('metaDataServices', 'MetaDataServiceController');

Route::resource('offers', 'OfferController');

Route::resource('orderItems', 'OrderItemController');

Route::resource('ownerSources', 'OwnerSourceController');

Route::resource('receipts', 'ReceiptController');

Route::resource('users', 'UserController');

Route::resource('orders', 'OrderController');

Route::resource('customerSessions', 'CustomerSessionController');

Route::resource('favoris', 'FavoriController');

Route::resource('foodSpeialties', 'FoodSpeialtiesController');

Route::resource('excursionActivities', 'ExcursionActivityController');

// Customer Routes
Route::post('/orders/storeAjax','OrderController@insertOrderData');

Route::resource('customerDevices', 'CustomerDeviceController');
Route::resource('hotelSpecifications', 'HotelSpecificationController');

Route::resource('otps', 'OtpController');


// Route::post('/orders/storeAjax', "OrderController@storeAjax")->name('orders.storeAjax');
Route::post('/orders/storeAjax', "OrderController@storeAjax")->name('orders.storeAjax');

Route::get('adjeminPay/{id}', function($id){
    // dump($id);
    $transaction = InvoicePayment::find($id);
    $payment_method = $transaction->payment_method;
    $transactionId = $transaction->payment_reference;
    $transaction_designation = $transaction->payment_gateway_designation;
    $amount = $transaction->amount;
    $status = $transaction->status;
    $customer = $transaction->creator_name;
    $customer_id = $transaction->creator_id;
    $notification = $transaction->invoice_id;
    $currency = $transaction->currency_code;
    // dd($transaction);

    if($transaction !== null){
        // return 'ok';
        return view('adjeminpay.index', compact('payment_method', 'transactionId', 'transaction_designation', 'amount','currency', 'status', 'customer', 'notification','customer_id', 'transaction'));
        // return view("cinetpay.index");
    }

});

Route::get('notify/{id}', 'AdjeminPayController@changeStatus');


// Route::get('cinetPay/{id}', function($id){
//     dd($id);

//     $transaction = InvoicePayment::find($id);
//     $payment_method = $transaction->payment_method;
//     $transactionId = $transaction->payment_reference;
//     $transaction_designation = $transaction->payment_gateway_designation;
//     $amount = $transaction->amount;
//     $status = $transaction->status;
//     $customer = $transaction->creator_name;
//     $customer_id = $transaction->creator_id;
//     $notification = $transaction->invoice_id;

//     if($transaction !== null){
//         // return 'ok';
//         // return view("cinetpay.index");
//         return view('cinetpay.index', compact('payment_method', 'transactionId', 'transaction_designation', 'amount', 'status', 'customer', 'notification','customer_id'));
//     }
// });


Route::resource('transcations', 'TranscationController');

app/Models/CustomerDevice.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * @SWG\Definition(
 *      definition="CustomerDevice",
 *      required={""},
 *      @SWG\Property(
 *          property="id",
 *          description="id",
 *          type="integer",
 *          format="int32"
 *      ),
 *      @SWG\Property(
 *          property="customer_id",
 *          description="customer_id",
 *          type="integer",
 *          format="int32"
 *      ),
 *      @SWG\Property(
 *          property="firebase_id",
 *          description="firebase_id",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="device_id",
 *          description="device_id",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="device_model",
 *          description="device_model",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="device_os",
 *          description="device_os",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="device_os_version",
 *          description="device_os_version",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="device_model_type",
 *          description="device_model_type",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="device_meta_data",
 *          description="device_meta_data",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="created_at",
 *          description="created_at",
 *          type="string",
 *          format="date-time"
 *      ),
 *      @SWG\Property(
 *          property="updated_at",
 *          description="updated_at",
 *          type="string",
 *          format="date-time"
 *      )
 * )
 */
class CustomerDevice extends Model
{
    use SoftDeletes;

    public $table = 'customer_devices';
    

    protected $dates = ['deleted_at'];



    public $fillable = [
        'customer_id',
        'firebase_id',
        'device_id',
        'device_model',
        'device_os',
        'device_os_version',
        'device_model_type',
        'device_meta_data'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'customer_id' => 'integer',
        'firebase_id' => 'string',
        'device_id' => 'string',
        'device_model' => 'string',
        'device_os' => 'string',
        'device_os_version' => 'string',
        'device_model_type' => 'string',
        'device_meta_data' => 'string'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        
    ];

    
}

app/Http/Controllers/CustomerDeviceController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateCustomerDeviceRequest;
use App\Http\Requests\UpdateCustomerDeviceRequest;
use App\Repositories\CustomerDeviceRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;
use Response;

class CustomerDeviceController extends AppBaseController
{
    /** @var  CustomerDeviceRepository */
    private $customerDeviceRepository;

    public function __construct(CustomerDeviceRepository $customerDeviceRepo)
    {
        $this->customerDeviceRepository = $customerDeviceRepo;
    }

    /**
     * Display a listing of the CustomerDevice.
     *
     * @param Request $request
     *
     * @return Response
     */
    public function index(Request $request)
    {
        $customerDevices = $this->customerDeviceRepository->all();

        return view('customer_devices.index')
            ->with('customerDevices', $customerDevices);
    }

    /**
     * Show the form for creating a new CustomerDevice.
     *
     * @return Response
     */
    public function create()
    {
        return view('customer_devices.create');
    }

    /**
     * Store a newly created CustomerDevice in storage.
     *
     * @param CreateCustomerDeviceRequest $request
     *
     * @return Response
     */
    public function store(CreateCustomerDeviceRequest $request)
    {
        $input = $request->all();

        $customerDevice = $this->customerDeviceRepository->create($input);

        Flash::success('Customer Device saved successfully.');

        return redirect(route('customerDevices.index'));
    }

    /**
     * Display the specified CustomerDevice.
     *
     * @param int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $customerDevice = $this->customerDeviceRepository->find($id);

        if (empty($customerDevice)) {
            Flash::error('Customer Device not found');

            return redirect(route('customerDevices.index'));
        }

        return view('customer_devices.show')->with('customerDevice', $customerDevice);
    }

    /**
     * Show the form for editing the specified CustomerDevice.
     *
     * @param int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $customerDevice = $this->customerDeviceRepository->find($id);

        if (empty($customerDevice)) {
            Flash::error('Customer Device not found');

            return redirect(route('customerDevices.index'));
        }

        return view('customer_devices.edit')->with('customerDevice', $customerDevice);
    }

    /**
     * Update the specified CustomerDevice in storage.
     *
     * @param int $id
     * @param UpdateCustomerDeviceRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateCustomerDeviceRequest $request)
    {
        $customerDevice = $this->customerDeviceRepository->find($id);

        if (empty($customerDevice)) {
            Flash::error('Customer Device not found');

            return redirect(route('customerDevices.index'));
        }

        $customerDevice = $this->customerDeviceRepository->update($request->all(), $id);

        Flash::success('Customer Device updated successfully.');

        return redirect(route('customerDevices.index'));
    }

    /**
     * Remove the specified CustomerDevice from storage.
     *
     * @param int $id
     *
     * @throws \Exception
     *
     * @return Response
     */
    public function destroy($id)
    {
        $customerDevice = $this->customerDeviceRepository->find($id);

        if (empty($customerDevice)) {
            Flash::error('Customer Device not found');

            return redirect(route('customerDevices.index'));
        }

        $this->customerDeviceRepository->delete($id);

        Flash::success('Customer Device deleted successfully.');

        return redirect(route('customerDevices.index'));
    }
}

resources/views/customer_devices/create.blade.php
@extends('layouts.app')

@section('content')
    <ol class="breadcrumb">
      <li class="breadcrumb-item">
         <a href="{!! route('customerDevices.index') !!}">Customer Device</a>
      </li>
      <li class="breadcrumb-item active">Create</li>
    </ol>
     <div class="container-fluid">
          <div class="animated fadeIn">
                @include('coreui-templates::common.errors')
                <div class="row">
                    <div class="col-lg-12">
                        <div class="card">
                            <div class="card-header">
                                <i class="fa fa-plus-square-o fa-lg"></i>
                                <strong>Create Customer Device</strong>
                            </div>
                            <div class="card-body">
                                {!! Form::open(['route' => 'customerDevices.store']) !!}

                                   @include('customer_devices.fields')

                                {!! Form::close() !!}
                            </div>
                        </div>
                    </div>
                </div>
           </div>
    </div>
@endsection

resources/views/customer_devices/edit.blade.php
@extends('layouts.app')

@section('content')
    <ol class="breadcrumb">
          <li class="breadcrumb-item">
             <a href="{!! route('customerDevices.index') !!}">Customer Device</a>
          </li>
          <li class="breadcrumb-item active">Edit</li>
        </ol>
    <div class="container-fluid">
         <div class="animated fadeIn">
             @include('coreui-templates::common.errors')
             <div class="row">
                 <div class="col-lg-12">
                      <div class="card">
                          <div class="card-header">
                              <i class="fa fa-edit fa-lg"></i>
                              <strong>Edit Customer Device</strong>
                          </div>
                          <div class="card-body">
                              {!! Form::model($customerDevice, ['route' => ['customerDevices.update', $customerDevice->id], 'method' => 'patch']) !!}

                              @include('customer_devices.fields')

                              {!! Form::close() !!}
                            </div>
                        </div>
                    </div>
                </div>
         </div>
    </div>
@endsection

resources/views/customer_devices/fields.blade.php
<!-- Customer Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('customer_id', 'Customer Id:') !!}
    {!! Form::number('customer_id', null, ['class' => 'form-control']) !!}
</div>

<!-- Firebase Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('firebase_id', 'Firebase Id:') !!}
    {!! Form::text('firebase_id', null, ['class' => 'form-control']) !!}
</div>

<!-- Device Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('device_id', 'Device Id:') !!}
    {!! Form::text('device_id', null, ['class' => 'form-control']) !!}
</div>

<!-- Device Model Field -->
<div class="form-group col-sm-6">
    {!! Form::label('device_model', 'Device Model:') !!}
    {!! Form::text('device_model', null, ['class' => 'form-control']) !!}
</div>

<!-- Device Os Field -->
<div class="form-group col-sm-6">
    {!! Form::label('device_os', 'Device Os:') !!}
    {!! Form::text('device_os', null, ['class' => 'form-control']) !!}
</div>

<!-- Device Os Version Field -->
<div class="form-group col-sm-6">
    {!! Form::label('device_os_version', 'Device Os Version:') !!}
    {!! Form::text('device_os_version', null, ['class' => 'form-control']) !!}
</div>

<!-- Device Model Type Field -->
<div class="form-group col-sm-6">
    {!! Form::label('device_model_type', 'Device Model Type:') !!}
    {!! Form::text('device_model_type', null, ['class' => 'form-control']) !!}
</div>

<!-- Device Meta Data Field -->
<div class="form-group col-sm-6">
    {!! Form::label('device_meta_data', 'Device Meta Data:') !!}
    {!! Form::text('device_meta_data', null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{{ route('customerDevices.index') }}" class="btn btn-secondary">Cancel</a>
</div>

resources/views/customer_devices/index.blade.php
@extends('layouts.app')

@section('content')
    <ol class="breadcrumb">
        <li class="breadcrumb-item">Customer Devices</li>
    </ol>
    <div class="container-fluid">
        <div class="animated fadeIn">
             @include('flash::message')
             <div class="row">
                 <div class="col-lg-12">
                     <div class="card">
                         <div class="card-header">
                             <i class="fa fa-align-justify"></i>
                             CustomerDevices
                             <a class="pull-right" href="{{ route('customerDevices.create') }}"><i class="fa fa-plus-square fa-lg"></i></a>
                         </div>
                         <div class="card-body">
                             @include('customer_devices.table')
                              <div class="pull-right mr-3">
                                     
                              </div>
                         </div>
                     </div>
                  </div>
             </div>
         </div>
    </div>
@endsection

resources/views/customer_devices/show.blade.php
@extends('layouts.app')

@section('content')
     <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="{{ route('customerDevices.index') }}">Customer Device</a>
            </li>
            <li class="breadcrumb-item active">Detail</li>
     </ol>
     <div class="container-fluid">
          <div class="animated fadeIn">
                 @include('coreui-templates::common.errors')
                 <div class="row">
                     <div class="col-lg-12">
                         <div class="card">
                             <div class="card-header">
                                 <strong>Details</strong>
                                  <a href="{{ route('customerDevices.index') }}" class="btn btn-light">Back</a>
                             </div>
                             <div class="card-body">
                                 @include('customer_devices.show_fields')
                             </div>
                         </div>
                     </div>
                 </div>
          </div>
    </div>
@endsection

resources/views/customer_devices/show_fields.blade.php
<!-- Customer Id Field -->
<div class="form-group">
    {!! Form::label('customer_id', 'Customer Id:') !!}
    <p>{{ $customerDevice->customer_id }}</p>
</div>

<!-- Firebase Id Field -->
<div class="form-group">
    {!! Form::label('firebase_id', 'Firebase Id:') !!}
    <p>{{ $customerDevice->firebase_id }}</p>
</div>

<!-- Device Id Field -->
<div class="form-group">
    {!! Form::label('device_id', 'Device Id:') !!}
    <p>{{ $customerDevice->device_id }}</p>
</div>

<!-- Device Model Field -->
<div class="form-group">
    {!! Form::label('device_model', 'Device Model:') !!}
    <p>{{ $customerDevice->device_model }}</p>
</div>

<!-- Device Os Field -->
<div class="form-group">
    {!! Form::label('device_os', 'Device Os:') !!}
    <p>{{ $customerDevice->device_os }}</p>
</div>

<!-- Device Os Version Field -->
<div class="form-group">
    {!! Form::label('device_os_version', 'Device Os Version:') !!}
    <p>{{ $customerDevice->device_os_version }}</p>
</div>

<!-- Device Model Type Field -->
<div class="form-group">
    {!! Form::label('device_model_type', 'Device Model Type:') !!}
    <p>{{ $customerDevice->device_model_type }}</p>
</div>

<!-- Device Meta Data Field -->
<div class="form-group">
    {!! Form::label('device_meta_data', 'Device Meta Data:') !!}
    <p>{{ $customerDevice->device_meta_data }}</p>
</div>

<!-- Created At Field -->
<div class="form-group">
    {!! Form::label('created_at', 'Created At:') !!}
    <p>{{ $customerDevice->created_at }}</p>
</div>

<!-- Updated At Field -->
<div class="form-group">
    {!! Form::label('updated_at', 'Updated At:') !!}
    <p>{{ $customerDevice->updated_at }}</p>
</div>

resources/views/customer_devices/table.blade.php
<div class="table-responsive-sm">
    <table class="table table-striped" id="customerDevices-table">
        <thead>
            <tr>
                <th>Customer Id</th>
        <th>Firebase Id</th>
        <th>Device Id</th>
        <th>Device Model</th>
        <th>Device Os</th>
        <th>Device Os Version</th>
        <th>Device Model Type</th>
        <th>Device Meta Data</th>
                <th colspan="3">Action</th>
            </tr>
        </thead>
        <tbody>
        @foreach($customerDevices as $customerDevice)
            <tr>
                <td>{{ $customerDevice->customer_id }}</td>
            <td>{{ $customerDevice->firebase_id }}</td>
            <td>{{ $customerDevice->device_id }}</td>
            <td>{{ $customerDevice->device_model }}</td>
            <td>{{ $customerDevice->device_os }}</td>
            <td>{{ $customerDevice->device_os_version }}</td>
            <td>{{ $customerDevice->device_model_type }}</td>
            <td>{{ $customerDevice->device_meta_data }}</td>
                <td>
                    {!! Form::open(['route' => ['customerDevices.destroy', $customerDevice->id], 'method' => 'delete']) !!}
                    <div class='btn-group'>
                        <a href="{{ route('customerDevices.show', [$customerDevice->id]) }}" class='btn btn-ghost-success'><i class="fa fa-eye"></i></a>
                        <a href="{{ route('customerDevices.edit', [$customerDevice->id]) }}" class='btn btn-ghost-info'><i class="fa fa-edit"></i></a>
                        {!! Form::button('<i class="fa fa-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-ghost-danger', 'onclick' => "return confirm('Are you sure?')"]) !!}
                    </div>
                    {!! Form::close() !!}
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>