routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Models\Customer;
use App\Models\InvoicePayment;
use App\Models\Offer;

Route::get('/', function () {
    $hotels = Offer::where('type', '=', 'hotel')->take(4)->get();
    $restaurants = Offer::where('type', '=', 'restaurant')->take(4)->get();


    $excursion = Offer::where('type', '=', 'excursion')->take(4)->get();
    return view('front.index', compact('hotels', 'restaurants','excursion'));
    });

Route::get('firebase_otp_verification', [HomeController::class, 'otpVerification']);

// Route::view("/", "front.index")->name('front.end.home');
// Route::get("/", "HomeController@index")->name('front.index');

Route::get('test', function(){
    return view('test');
});

// Make order ready
Route::get('/order-make-ready/{id}', 'OrderController@makeOrderReady')->name('order-make-ready');
Route::get('/order-make-ready-for-delivery/{id}', 'OrderController@makeOrderReadyForDelivery')->name('order-make-ready-for-delivery');
Route::get('/order-make-ready-for-cancelled/{id}', 'OrderController@makeOrderReadyCancelled')->name('order-make-ready-for-cancelled');
Route::get('/invoicepdf/{id}', 'OrderController@invoicePDF')->name('invoicepdf');

// Route excursion and excursionBooking
Route::get("/excursion", "ExcursionActivityController@indexFront")->name('excursion');
Route::get("/excursion-detail/{id}", "ExcursionActivityController@showFront")->name('excursion-detail');
Route::get("/formulaire-de-Reservation/{id}", "ExcursionActivityController@requestFormex")->name('request-formulaire')->middleware('customer.auth');



Route::get('checkIfUserExist','CustomerController@checkIfUserExist')->name('checkIfUserExist');
Route::get('loginUsingId','CustomerController@logUser')->name('loginUsingId');

//Customer
Route::get('/customerProfil/{id}', 'CustomerController@profil')->name('customerProfile');
Route::get('/editProfil/{id}', 'CustomerController@editProfil')->name('editProfil');
Route::put('/updateProfile/{id}', 'CustomerController@updateProfile')->name('updateProfile');

Route::get('/customerRequest/{id}', 'CustomerController@allCustomerOrders')->name('customerRequest');

// Route musee
Route::get("/musees", "MuseeController@index")->name('musee');
Route::get("/musee-detail/{id}", "MuseeController@show")->name('musee-detail');

// Route restaurant
Route::get("/restaurant-detail/{id}", "RestaurantController@show")->name('restaurant-detail');
Route::get("/view/restaurants", "RestaurantController@index");
Route::get("/view/Allrestaurants", "RestaurantController@indexAll")->name('All-restaurant');

// Route hotel, residence, HotelBooking and ResidenceBooking
Route::get("/view/hotels", "HotelController@index");
Route::get("/hotel-detail/{id}", "HotelController@show")->name('hotel-detail');
Route::get("/residence-detail/{id}", "HotelController@showes")->name('residence-detail');
// Route::get("/formulaire_Reservation/{id}", "HotelController@requestFormulaire")->name('request_formular')->middleware('customer.auth');


Route::get("/view/Allhotel", "HotelController@indexAll")->name('All-Hotel');
Route::get("/view/AllResidences", "HotelController@indexAlls")->name('All-Residences');

// Route location and locationBooking
Route::get("/location", "LocationController@index");
Route::get("/location-detail/{id}", "LocationController@show")->name('location-detail');
// Route::get("/formulaire_de_Reservation/{id}", "LocationController@requestForm")->name('request_form');
Route::get("/formulaire_de_Reservation/{id}", "LocationController@requestForm")->name('request_form')->middleware('customer.auth');

// Bedroom
Route::get("/bedroom-detail/{id}", "HotelController@ShowBedroom")->name('bedroom-detail');

// Request Formulaire
Route::get("/formulaireReservation/{id}", "HotelController@requestFormulaireBedroom")->name('request_formulaires')->middleware('customer.auth');

Route::get("/formulaireReservationResidence/{id}", "HotelController@requestFormulaireBedroom")->name('request_formular')->middleware('customer.auth');
// ->middleware('customer.auth');

Route::get('/storeAdjeminPay', "AdjeminPayController@storeAdjeminPay")->name('storeAdjeminPay');


// Route::view("/hotel-detail", "front.hotel_detail");
// Route::view("/restaurant-detail", "front.restaurant_detail");
// Route::view("/view/restaurants", "front.restaurants");
// Route::view("/view/hotels", "front.hotels");
// Route::view("/location", "front.location");

Route::view("/_", "_");    // Test view

Auth::routes(['verify' => true]);

Auth::routes(['register' => false]);

Route::get('/home', 'HomeController@index')->middleware('verified');
//
Route::resource('hotels', 'HotelController');
Route::resource('locations', 'LocationController');
Route::resource('restaurants', 'RestaurantController');

Route::name ('offer.')->middleware ('ajax')->group (function () {
    Route::prefix('offer')->group(function () {
    });
    Route::name ('rating')->put ('rating/{offer}', 'OfferController@rate');
});


Route::get('/restaurant_by_specification/{speciality}', 'RestaurantController@restaurantBySpecification');

Route::get('/excursion_by_specification/{speciality}', 'ExcursionActivityController@excursionBySpecification');


Route::resource('customers', 'CustomerController');

Route::resource('invoices', 'InvoiceController');

Route::resource('invoicePayments', 'InvoicePaymentController');

Route::resource('metaDataServices', 'MetaDataServiceController');

Route::resource('offers', 'OfferController');

Route::resource('orderItems', 'OrderItemController');

Route::resource('ownerSources', 'OwnerSourceController');

Route::resource('receipts', 'ReceiptController');

Route::resource('users', 'UserController');

Route::resource('orders', 'OrderController');

Route::resource('customerSessions', 'CustomerSessionController');

Route::resource('favoris', 'FavoriController');

Route::resource('foodSpeialties', 'FoodSpeialtiesController');

Route::resource('excursionActivities', 'ExcursionActivityController');

// Customer Routes
Route::post('/orders/storeAjax','OrderController@insertOrderData');

Route::resource('customerDevices', 'CustomerDeviceController');
Route::resource('hotelSpecifications', 'HotelSpecificationController');

Route::resource('otps', 'OtpController');


// Route::post('/orders/storeAjax', "OrderController@storeAjax")->name('orders.storeAjax');
Route::post('/orders/storeAjax', "OrderController@storeAjax")->name('orders.storeAjax');

Route::get('adjeminPay/{id}', function($id){
    // dump($id);
    $transaction = InvoicePayment::find($id);
    $payment_method = $transaction->payment_method;
    $transactionId = $transaction->payment_reference;
    $transaction_designation = $transaction->payment_gateway_designation;
    $amount = $transaction->amount;
    $status = $transaction->status;
    $customer = $transaction->creator_name;
    $customer_id = $transaction->creator_id;
    $notification = $transaction->invoice_id;
    $currency = $transaction->currency_code;
    // dd($transaction);

    if($transaction !== null){
        // return 'ok';
        return view('adjeminpay.index', compact('payment_method', 'transactionId', 'transaction_designation', 'amount','currency', 'status', 'customer', 'notification','customer_id', 'transaction'));
        // return view("cinetpay.index");
    }

});

Route::get('notify/{id}', 'AdjeminPayController@changeStatus');


// Route::get('cinetPay/{id}', function($id){
//     dd($id);

//     $transaction = InvoicePayment::find($id);
//     $payment_method = $transaction->payment_method;
//     $transactionId = $transaction->payment_reference;
//     $transaction_designation = $transaction->payment_gateway_designation;
//     $amount = $transaction->amount;
//     $status = $transaction->status;
//     $customer = $transaction->creator_name;
//     $customer_id = $transaction->creator_id;
//     $notification = $transaction->invoice_id;

//     if($transaction !== null){
//         // return 'ok';
//         // return view("cinetpay.index");
//         return view('cinetpay.index', compact('payment_method', 'transactionId', 'transaction_designation', 'amount', 'status', 'customer', 'notification','customer_id'));
//     }
// });


Route::resource('transcations', 'TranscationController');

app/Models/Offer.php
<?php

namespace App\Models;

use Eloquent as Model;
use App\Models\Favori;
use App\Models\OrderItem;
use App\Models\Customer;
use Illuminate\Database\Eloquent\SoftDeletes;
use App\Models\HotelSpecification;
use App\Models\Hotel;
use App\Models\Geographical;


/**
 * @SWG\Definition(
 *      definition="Offer",
 *      required={""},
 *      @SWG\Property(
 *          property="id",
 *          description="id",
 *          type="integer",
 *          format="int32"
 *      ),
 *      @SWG\Property(
 *          property="parent_source_id",
 *          description="parent_source_id",
 *          type="integer",
 *          format="int32"
 *      ),
 *      @SWG\Property(
 *          property="title",
 *          description="title",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="meta_data",
 *          description="meta_data",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="type",
 *          description="type",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="owner_id",
 *          description="owner_id",
 *          type="integer",
 *          format="int32"
 *      ),
 *      @SWG\Property(
 *          property="publisher_id",
 *          description="publisher_id",
 *          type="integer",
 *          format="int32"
 *      ),
 *      @SWG\Property(
 *          property="has_children",
 *          description="has_children",
 *          type="boolean"
 *      ),
 *      @SWG\Property(
 *          property="description",
 *          description="description",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="original_price",
 *          description="original_price",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="price",
 *          description="price",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="currency_code",
 *          description="currency_code",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="has_price",
 *          description="has_price",
 *          type="boolean"
 *      ),
 *      @SWG\Property(
 *          property="rating",
 *          description="rating",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="location_name",
 *          description="location_name",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="location_lat",
 *          description="location_lat",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="location_lng",
 *          description="location_lng",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="location_gps",
 *          description="location_gps",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="slide_url",
 *          description="slide_url",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="slide_title",
 *          description="slide_title",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="is_escort",
 *          description="is_escort",
 *          type="boolean"
 *      ),
 *      @SWG\Property(
 *          property="escort_fees",
 *          description="escort_fees",
 *          type="string"
 *      ),
 *      @SWG\Property(
 *          property="created_at",
 *          description="created_at",
 *          type="string",
 *          format="date-time"
 *      ),
 *      @SWG\Property(
 *          property="updated_at",
 *          description="updated_at",
 *          type="string",
 *          format="date-time"
 *      ),
 *      @SWG\Property(
 *          property="deleted_at",
 *          description="deleted_at",
 *          type="string",
 *          format="date-time"
 *      )
 * )
 */
class Offer extends Model
{
    use SoftDeletes;

    use Geographical;

    public $table = 'offers';

    const CREATED_AT = 'created_at';
    const UPDATED_AT = 'updated_at';

    const LATITUDE  = 'location_lat';
    const LONGITUDE = 'location_lng';


    protected $dates = ['deleted_at'];

    protected static $kilometers = true;

    public function getRouteKeyName(){
        return 'slug';
    }

    public $fillable = [
        'parent_source_id',
        'title',
        'slug',
        'meta_data',
        'type',
        'owner_id',
        'publisher_id',
        'publisher_name',
        'has_children',
        'description',
        'original_price',
        'price',
        'currency_code',
        'has_price',
        'rating',
        'location_name',
        'picture1',
        'picture2',
        'picture3',
        'picture4',
        'website',
        'phone_number',
        'room',
        'etalissement',
        'location_lat',
        'location_lng',
        'location_gps',
        'slide_url',
        'slide_title',
        'is_escort',
        'escort_fees'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'parent_source_id' => 'integer',
        'title' => 'string',
        'meta_data' => 'string',
        'type' => 'string',
        'owner_id' => 'integer',
        'publisher_id' => 'integer',
        'publisher_name' => 'string',
        'has_children' => 'boolean',
        'description' => 'string',
        'original_price' => 'string',
        'price' => 'string',
        'currency_code' => 'string',
        'has_price' => 'boolean',
        'rating' => 'string',
        'location_name' => 'string',
        'picture1' => 'string',
        'picture2' => 'string',
        'picture3' => 'string',
        'picture4' => 'string',
        'website' => 'string',
        'phone_number' => 'string',
        'room' => 'string',
        'etalissement' => 'string',
        'location_lat' => 'string',
        'location_lng' => 'string',
        'location_gps' => 'string',
        'slide_url' => 'string',
        'slide_title' => 'string',
        'is_escort' => 'boolean',
        'escort_fees' => 'string'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [

    ];

    public function favoris()
    {
        return $this->hasMany('App\Models\Favori', 'id');
    }

    public function orderitem()
    {
        return $this->hasMany('App\Models\OrderItem', 'id');
    }

    public function customer()
    {
        return $this->belongsTo('App\Models\Offer', 'owner_id');
    }

    public function bedrooms(){
        return $this->hasMany(Bedroom::class);
    }

    public function spec(){
        return $this->hasMany(HotelSpecification::class);
    }

    public function getSpecifications()
    {

        if (empty($this->specifications)) {
            return [];
        } else {
            return $this->specifications;
        }
    }

    public function FoodSpeialties(){
        return $this->belongsToMany('App\Models\FoodSpeialties');
    }

    public function getPictures(){
         $offer = Offer::orWhere(["id"=>$this->id])->get();

        //  dd(json_decode($offer[0]->meta_data));
         if($offer != null && count($offer) > 0) {
            $pictures = json_decode($offer[0]->meta_data)->pictures;
            return $pictures;
         }else{
             return 'not image found';
         }
    }
    // public function Customer()
    // {
    //     return $this->belongsToMany (customer::class)->withPivot('rating');
    // }
}

app/Offer_.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Offer extends Model
{
    //

    protected $guarded = [];

    //
    public function specifications()
    {
        return $this->hasMany(SpecificationHotel::class);
    }
}

resources/views/offers/create.blade.php
@extends('layouts.app')

@section('content')
    <ol class="breadcrumb">
      <li class="breadcrumb-item">
         <a href="{!! route('offers.index') !!}">Offres</a>
      </li>
      <li class="breadcrumb-item active">Créer</li>
    </ol>
     <div class="container-fluid">
          <div class="animated fadeIn">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="card">
                            <div class="card-header">
                                <i class="fa fa-plus-square-o fa-lg"></i>
                                <strong>Créer une offre</strong>
                            </div>
                            <div class="card-body">
                                {!! Form::open(['route' => 'offers.store', 'files'=>true ]) !!}
                                   {{-- @csrf --}}
                                   @include('offers.fields')

                                {!! Form::close() !!}
                            </div>
                        </div>
                    </div>
                </div>
           </div>
    </div>
@endsection

resources/views/offers/edit.blade.php
@extends('layouts.app')

@section('content')
    <ol class="breadcrumb">
          <li class="breadcrumb-item">
             <a href="{!! route('offers.index') !!}">Offres</a>
          </li>
          <li class="breadcrumb-item active">Modifier</li>
        </ol>
    <div class="container-fluid">
         <div class="animated fadeIn">
             <div class="row">
                 <div class="col-lg-12">
                      <div class="card">
                          <div class="card-header">
                              <i class="fa fa-edit fa-lg"></i>
                              <strong>Modifier une offre</strong>
                          </div>
                          <div class="card-body">
                              {!! Form::model($offer, ['route' => ['offers.update', $offer->id], 'method' => 'patch']) !!}

                              @include('offers.fields')

                              {!! Form::close() !!}
                            </div>
                        </div>
                    </div>
                </div>
         </div>
    </div>
@endsection

resources/views/offers/index.blade.php
@extends('layouts.app')

@section('content')
    <ol class="breadcrumb">
        <li class="breadcrumb-item">Offres</li>
    </ol>
    <div class="container-fluid">
        <div class="animated fadeIn">
             @include('flash::message')
             <div class="row">
                 <div class="col-lg-12">
                     <div class="card">
                         <div class="card-header">
                             <i class="fa fa-align-justify"></i>
                             Offres
                             <a class="pull-right" href="{{ route('offers.create') }}"><i class="fa fa-plus-square fa-lg"></i></a>
                         </div>
                         <div class="card-body">
                             @include('offers.table')
                              <div class="pull-right mr-3">

                              </div>
                         </div>
                     </div>
                  </div>
             </div>
         </div>
    </div>
@endsection

resources/views/offers/show.blade.php
@extends('layouts.app')

@section('content')
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a href="{{ route('offers.index') }}">Offres</a>
        </li>
        <li class="breadcrumb-item active">Detail</li>
    </ol>
    <div class="container-fluid">
        <div class="animated fadeIn">
            <div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-header">
                            <strong>Details Offre #{{ $offer->id ." : ".$offer->type."  ".$offer->title }}</strong>
                            <div>
                                {{-- <i class="fa fa-trash"></i>', --}}
                                {{-- Delete button --}}
                                {!! Form::button('Supprimer'
                                ,['type' => 'submit', 'class' => 'btn btn-danger', 'onclick' => "return confirm('Voulez-vous supprimer cette offre?')"]) !!}
                                {{-- Edit button --}}
                                <a href="{{ route('offers.edit', [$offer->id]) }}" class="btn btn-warning">Modifier</a>
                                {{-- Go back button --}}
                                <a href="{{ route('offers.index') }}" class="btn btn-light">Retour</a>
                            </div>
                        </div>
                        <div class="card-body">
                            @include('offers.show_fields')
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/offers/table.blade.php
<div class="box">

    <!-- /.box-header -->
    <div class="box-body" style="overflow-x: scroll;">
        <table id="example" class="table table-bordered table-hover display nowrap margin-top-10 table-responsive-sm">
            <thead>
                <tr>
                <th>Action</th>
                <th>Parent</th>
                <th>Titre</th>
                <th>Photo 1</th>
                <th>Photo 2</th>
                <th>Photo 3</th>
                <th>Photo 4</th>
                {{-- <th>Spécifications web/Telephone</th> --}}
                {{-- <th>Chambre/Résidence</th> --}}
                {{-- <th>Equipement établissement</th> --}}
                <th>Type</th>
                <th>Propriétaire</th>
                {{-- <th>Identifiant du créateur</th> --}}
                {{-- <th>Appartient a un type d'offre</th> --}}
                <th>Description</th>
                {{-- <th>Prix original</th> --}}
                {{-- <th>Prix</th> --}}
                {{-- <th>Code de la devise</th> --}}
                {{-- <th>A un prix</th> --}}
                {{-- <th>Note</th> --}}
                <th>Situation géograpique</th>
                {{-- <th>Latitude</th> --}}
                {{-- <th>Longitude</th> --}}
                {{-- <th>Gps</th> --}}
                <th>Slide</th>
                <th>Site Web</th>
                <th>Contact Téléphonique</th>
                {{-- <th>Titre du slide</th> --}}
                {{-- <th>Accompagné ?</th> --}}
                {{-- <th>Frais d'accompagnement</th> --}}
                <th>Action</th>
            </tr>
            </thead>
            <tbody>
            @forelse($offers->reverse() as $offer)
                <tr>
                    <td>
                        {!! Form::open(['route' => ['offers.destroy', $offer->id], 'method' => 'delete']) !!}
                        <div class='btn-group'>
                            <a href="{{ route('offers.show', [$offer->id]) }}" class='btn btn-success'><i
                                    class="fa fa-eye"></i></a>
                            <a href="{{ route('offers.edit', [$offer->id]) }}" class='btn btn-info'><i
                                    class="fa fa-edit"></i></a>
                            {!!
                                Form::button('<i class="fa fa-trash"></i>',
                                ['type' => 'submit', 'class' => 'btn btn-danger', 'onclick' => "return confirm('Are you sure?')"])
                            !!}

                        </div>
                        {!! Form::close() !!}
                    </td>
                    <td>
                        @if($offer->parent_source_id != 0)

                                <?php
                                echo (App\Models\Offer::where('id', $offer->parent_source_id)->get());
                                ?>
                                {{-- {{ ( json_decode($offer->getItemsAttribute()[0]->meta_data)->title ) }} --}}
                        @endif
                    </td>
                    <td>{{ $offer->title }}</td>
                    <td>
                        @if($offer->picture1 != null)
                            <img src="{{ $offer->picture1 }}" height="90" width="90">
                        @endif
                    </td>
                    <td>
                        @if($offer->picture2 != null)
                            <img src="{{ $offer->picture2 }}" height="90" width="90">
                        @endif
                    </td>
                    <td>
                        @if($offer->picture3 != null)
                            <img src="{{ $offer->picture3 }}" height="90" width="90">
                        @endif
                    </td>
                    <td>
                        @if($offer->picture3 != null)
                            <img src="{{ $offer->picture4 }}" height="90" width="90">
                        @endif
                    </td>
                    {{-- <td>@if($offer->specification != null)
                            {{$offer->specification}}
                        @endif
                    </td> --}}
                    {{-- <td>@if($offer->room != null)
                            {{$offer->room}}
                        @endif
                    </td> --}}
                    {{-- <td>@if($offer->etalissement != null)
                            {{$offer->etalissement}}
                        @endif
                    </td> --}}
                    <td>{{ $offer->type }}</td>
                    <td>
                        {{-- @if (!empty($offer->customer)) --}}
                            {{-- {{ $offer->customer->name }} --}}
                            @php
                            $owner = App\Models\Customer::find($offer->owner_id);
                                if(!empty($owner)){
                                    echo
                                    $owner->name;
                                } else {
                                    echo "Non_defini";
                                }
                            @endphp
                        {{-- @endif --}}
                        {{-- @if (!empty($offer->customer))
                            {{ $offer->customer->name }}
                        @endif --}}
                    </td>
                    {{-- <td>{{ $offer->publisher_id }}</td> --}}
                    {{-- <td>{{ $offer->publisher_name }}</td> --}}
                    {{-- <td>
                        @if($offer->has_children == 0)
                            Non
                        @else
                            Oui
                        @endif
                    </td> --}}
                    <td>{!! $offer->description !!}</td>
                    {{-- <td>{{ $offer->original_price }}</td>
                    <td>{{ $offer->price }}</td> --}}
                    {{-- <td>{{ $offer->currency_code }}</td> --}}
                    {{-- <td>
                        @if($offer->has_price == 0)
                            Non
                        @else
                            Oui
                        @endif
                    </td> --}}
                    {{-- <td>{{ $offer->rating }}</td> --}}
                    <td>{{ $offer->location_name }}</td>
                    {{--
                    <td>{{ $offer->location_lat }}</td>
                    <td>{{ $offer->location_lng }}</td>
                    <td>{{ $offer->location_gps }}</td>
                    --}}
                    <td>
                        <img src="{{ $offer->slide_url  }}" height="90" width="90">
                    </td>
                    <td>{{ $offer->website }}</td>
                    <td>{{ $offer->phone_number }}</td>
                    {{-- <td>{{ $offer->slide_title }}</td> --}}
                    {{-- <td>
                        @if($offer->is_escort == 0)
                            Non
                        @else
                            Oui
                        @endif
                    </td> --}}
                    {{-- <td>{{ $offer->escort_fees }}</td> --}}
                    <td>

                        {!! Form::open(['route' => ['offers.destroy', $offer->id], 'method' => 'delete']) !!}
                        <div class='btn-group'>
                            <a href="{{ route('offers.show', [$offer->id]) }}" class='btn btn-success'><i
                                    class="fa fa-eye"></i></a>
                            <a href="{{ route('offers.edit', [$offer->id]) }}" class='btn btn-info'><i
                                    class="fa fa-edit"></i></a>
                            {!!
                                Form::button('<i class="fa fa-trash"></i>',
                                ['type' => 'submit', 'class' => 'btn btn-danger', 'onclick' => "return confirm('Are you sure?')"])
                            !!}

                        </div>
                        {!! Form::close() !!}
                    </td>
                </tr>
            @empty
                <div class="d-flex justify-content-center">
                    Aucune commande éffectuée.
                </div>
            @endforelse
            </tbody>
        </table>
    </div>
</div>